sonar.projectKey=lugialo_social-digital-laravel
sonar.projectName=Social Digital Laravel
sonar.organization=lugialo

sonar.sources=app,routes,config
sonar.tests=tests
sonar.exclusions=vendor/**,node_modules/**,public/**,storage/**,bootstrap/cache/**

sonar.php.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=app/Console/**,app/Exceptions/**,database/**,resources/**

sonar.sourceEncoding=UTF-8
